<img src='https://user-images.githubusercontent.com/6457691/89746244-a6e2a200-daf3-11ea-9314-7863d544d73c.png' width = '200' align = 'right'>

## *DATA SCIENCE / SECTION 1 / SPRINT 2 / NOTE 3*

---

# 📝 Assignment

In [1]:
# 아래의 코드를 실행해 주세요. 
!pip install scipy --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (1.7.3)
Requirement already satisfied: numpy<1.23.0,>=1.16.5 in /usr/local/lib/python3.7/dist-packages (from scipy) (1.21.6)

In [2]:
# 버전 확인 
import scipy

scipy.__version__

'1.7.3'

# 1. One-Sample T-test 
한 샘플의 평균값과 특정값(모수)을 비교하는 검정 방법입니다.

$H_0$ : $\mu_{sample} = \mu_{population}$

$H_a$ : $\mu_{sample} ≠ \mu_{population}$ 

- 데이터 불러오기 <br>
  [서울시 가로수 데이터셋](https://data.seoul.go.kr/dataList/367/S/2/datasetView.do)을 사용합니다. 다음 링크를 참조하세요. <br>
<https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/seoul_tree/seoul_tree.txt>

- 서울시 구별 `이팝나무` 데이터를 모집단으로 하였을 때, 10개의 구를 샘플링한 `이팝나무` 수의 평균과 모집단의 평균을 비교하는 가설검정을 시행하세요.   
  - `서울시`, `공원녹지사업소`, `시설관리공단` 데이터는 제외합니다. 
  - 10개의 구를 중복을 허용하여 샘플링합니다. 
    - seed는 123으로 설정하세요. 
  - scipy 라이브러리의 `.ttest_1samp()`를 사용합니다. <br>
    https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_1samp.html
  - 가설검정 결과의 p-value 값을 `pv1`에 저장하세요. (`.pvalue`를 사용합니다.)

In [3]:
# 이 곳에 답안을 작성하시기 바랍니다.
import pandas as pd
import numpy as np
url = 'https://ds-lecture-data.s3.ap-northeast-2.amazonaws.com/seoul_tree/seoul_tree.txt'
tree = pd.read_table(url)

tree

,기간,자치구,노선수,수량,종별,종별.1,종별.2,종별.3,종별.4,종별.5,...,종별.10,종별.11,종별.12,종별.13,종별.14,종별.15,종별.16,종별.17,종별.18,종별.19
0,기간,자치구,노선수,수량,은행나무,양버즘나무,느티나무,왕벚나무,은단풍나무,메타세콰이어,...,튜울립나무,칠엽수,포플러,느릅나무,살구나무,무궁화,소나무,목련,이팝나무,기타
1,2019,서울시,"1,412","307,351","108,050","62,474","37,473","34,150",545,"5,171",...,948,"1,533",7,504,234,"2,374","4,539",378,"20,088","20,112"
2,2019,종로구,70,"7,329","4,072","1,071",619,421,-,1,...,-,17,-,-,-,-,239,-,711,29
3,2019,중구,48,"8,250","3,640",162,460,289,-,-,...,7,-,-,-,21,46,"2,162",-,470,817
4,2019,용산구,39,"7,835","4,444","1,422",373,262,-,-,...,13,16,-,-,39,-,51,126,198,780
5,2019,성동구,38,"8,120","1,090","2,401","1,975",602,29,48,...,-,1,3,59,-,-,53,-,709,646
6,2019,광진구,28,"7,223","1,247","2,306","1,057",940,-,-,...,58,101,-,-,-,-,20,113,760,443
7,2019,동대문구,43,"10,664","3,749","3,342",855,747,-,60,...,37,19,-,1,26,1,-,-,"1,176",456
8,2019,중랑구,57,"8,365","2,774","2,759",471,354,-,74,...,-,-,-,-,-,212,64,-,449,"1,156"
9,2019,성북구,78,"8,449","2,722","1,282","1,014","1,656",66,65,...,4,-,-,-,9,5,97,-,853,547
10,2019,강북구,31,"7,789","3,510",934,324,497,284,-,...,5,-,-,140,-,-,"1,007",-,575,410
11,2019,도봉구,63,"9,572","4,914",323,779,"2,095",6,61,...,15,-,-,-,-,214,15,-,47,"1,070"
12,2019,노원구,50,"14,489","6,505","3,336","1,165","1,612",-,285,...,-,-,-,26,58,150,32,1,142,"1,135"
13,2019,은평구,35,"9,880","4,324","1,653",680,"1,748",-,16,...,-,9,-,-,-,3,-,-,443,582
14,2019,서대문구,39,"8,627","3,474","1,890",721,732,-,25,...,10,5,4,-,-,70,-,-,493,"1,120"
15,2019,마포구,92,"14,538","3,353","3,581","3,056","1,096",-,474,...,-,-,-,-,64,-,124,93,"1,280",348
16,2019,양천구,69,"13,501","5,622","3,992","1,065",956,-,74,...,-,4,-,-,-,197,-,-,784,595
17,2019,강서구,55,"13,719","3,977",706,"2,231","2,508",-,"1,651",...,-,110,-,-,-,59,282,-,"1,426",568
18,2019,구로구,81,"11,548","3,594","1,527","1,884","2,157",13,3,...,-,17,-,-,-,-,30,26,"1,082","1,210"
19,2019,금천구,30,"6,603","3,545","1,024",407,"1,123",-,35,...,-,7,-,-,-,-,5,-,184,69
20,2019,영등포구,114,"18,220","5,879","3,439","3,419","2,952",147,51,...,12,174,-,-,-,-,40,19,"1,281",651
21,2019,동작구,29,"7,083","2,178",829,"1,421","1,127",-,116,...,-,-,-,-,-,206,7,-,397,794
22,2019,관악구,32,"10,154","2,280","2,188",185,"2,416",-,95,...,-,-,-,-,-,"1,120",59,-,249,"1,194"
23,2019,서초구,56,"16,548","3,800","5,036","3,409",254,-,"1,159",...,-,721,-,-,-,91,-,-,446,"1,143"
24,2019,강남구,60,"23,349","7,210","7,559","2,991","2,455",-,864,...,65,-,-,-,-,-,-,-,768,913
25,2019,송파구,99,"22,858","11,894","4,180","2,400",992,-,14,...,722,329,-,-,-,-,215,-,"1,651",450
26,2019,강동구,66,"17,152","5,474","4,284","2,417","2,309",-,-,...,-,-,-,-,-,-,-,-,642,"1,969"
27,2019,공원녹지사업소,1,236,179,26,24,-,-,-,...,-,3,-,-,-,-,-,-,4,-
28,2019,시설관리공단,9,"15,250","2,600","1,222","2,071","1,850",-,-,...,-,-,-,278,17,-,37,-,"2,868","1,017"

In [4]:
tree = tree[tree.자치구 != '서울시'] ##서울시, 공원녹지사업소, 시설관리공단 데이터는 제외합니다. 
tree = tree[tree.자치구 != '공원녹지사업소']
tree = tree[tree.자치구 != '시설관리공단']


a =[]
a = tree.iloc[0]   ### 열 이름 바꿔주기위해 저장해놓는 작업
tree = tree.rename(columns = a)    ## .종별x 말고 나무이름으로 바꿔줌.
tree = tree.drop([tree.index[0]]).reset_index(drop=True)   ### 첫행 삭제 후 인덱스 재정렬
tree

,기간,자치구,노선수,수량,은행나무,양버즘나무,느티나무,왕벚나무,은단풍나무,메타세콰이어,...,튜울립나무,칠엽수,포플러,느릅나무,살구나무,무궁화,소나무,목련,이팝나무,기타
0,2019,종로구,70,"7,329","4,072","1,071",619,421,-,1,...,-,17,-,-,-,-,239,-,711,29
1,2019,중구,48,"8,250","3,640",162,460,289,-,-,...,7,-,-,-,21,46,"2,162",-,470,817
2,2019,용산구,39,"7,835","4,444","1,422",373,262,-,-,...,13,16,-,-,39,-,51,126,198,780
3,2019,성동구,38,"8,120","1,090","2,401","1,975",602,29,48,...,-,1,3,59,-,-,53,-,709,646
4,2019,광진구,28,"7,223","1,247","2,306","1,057",940,-,-,...,58,101,-,-,-,-,20,113,760,443
5,2019,동대문구,43,"10,664","3,749","3,342",855,747,-,60,...,37,19,-,1,26,1,-,-,"1,176",456
6,2019,중랑구,57,"8,365","2,774","2,759",471,354,-,74,...,-,-,-,-,-,212,64,-,449,"1,156"
7,2019,성북구,78,"8,449","2,722","1,282","1,014","1,656",66,65,...,4,-,-,-,9,5,97,-,853,547
8,2019,강북구,31,"7,789","3,510",934,324,497,284,-,...,5,-,-,140,-,-,"1,007",-,575,410
9,2019,도봉구,63,"9,572","4,914",323,779,"2,095",6,61,...,15,-,-,-,-,214,15,-,47,"1,070"
10,2019,노원구,50,"14,489","6,505","3,336","1,165","1,612",-,285,...,-,-,-,26,58,150,32,1,142,"1,135"
11,2019,은평구,35,"9,880","4,324","1,653",680,"1,748",-,16,...,-,9,-,-,-,3,-,-,443,582
12,2019,서대문구,39,"8,627","3,474","1,890",721,732,-,25,...,10,5,4,-,-,70,-,-,493,"1,120"
13,2019,마포구,92,"14,538","3,353","3,581","3,056","1,096",-,474,...,-,-,-,-,64,-,124,93,"1,280",348
14,2019,양천구,69,"13,501","5,622","3,992","1,065",956,-,74,...,-,4,-,-,-,197,-,-,784,595
15,2019,강서구,55,"13,719","3,977",706,"2,231","2,508",-,"1,651",...,-,110,-,-,-,59,282,-,"1,426",568
16,2019,구로구,81,"11,548","3,594","1,527","1,884","2,157",13,3,...,-,17,-,-,-,-,30,26,"1,082","1,210"
17,2019,금천구,30,"6,603","3,545","1,024",407,"1,123",-,35,...,-,7,-,-,-,-,5,-,184,69
18,2019,영등포구,114,"18,220","5,879","3,439","3,419","2,952",147,51,...,12,174,-,-,-,-,40,19,"1,281",651
19,2019,동작구,29,"7,083","2,178",829,"1,421","1,127",-,116,...,-,-,-,-,-,206,7,-,397,794
20,2019,관악구,32,"10,154","2,280","2,188",185,"2,416",-,95,...,-,-,-,-,-,"1,120",59,-,249,"1,194"
21,2019,서초구,56,"16,548","3,800","5,036","3,409",254,-,"1,159",...,-,721,-,-,-,91,-,-,446,"1,143"
22,2019,강남구,60,"23,349","7,210","7,559","2,991","2,455",-,864,...,65,-,-,-,-,-,-,-,768,913
23,2019,송파구,99,"22,858","11,894","4,180","2,400",992,-,14,...,722,329,-,-,-,-,215,-,"1,651",450
24,2019,강동구,66,"17,152","5,474","4,284","2,417","2,309",-,-,...,-,-,-,-,-,-,-,-,642,"1,969"

In [5]:
import random
tree['이팝나무'] = tree['이팝나무'].str.replace(',','').astype(int)
tree

,기간,자치구,노선수,수량,은행나무,양버즘나무,느티나무,왕벚나무,은단풍나무,메타세콰이어,...,튜울립나무,칠엽수,포플러,느릅나무,살구나무,무궁화,소나무,목련,이팝나무,기타
0,2019,종로구,70,"7,329","4,072","1,071",619,421,-,1,...,-,17,-,-,-,-,239,-,711,29
1,2019,중구,48,"8,250","3,640",162,460,289,-,-,...,7,-,-,-,21,46,"2,162",-,470,817
2,2019,용산구,39,"7,835","4,444","1,422",373,262,-,-,...,13,16,-,-,39,-,51,126,198,780
3,2019,성동구,38,"8,120","1,090","2,401","1,975",602,29,48,...,-,1,3,59,-,-,53,-,709,646
4,2019,광진구,28,"7,223","1,247","2,306","1,057",940,-,-,...,58,101,-,-,-,-,20,113,760,443
5,2019,동대문구,43,"10,664","3,749","3,342",855,747,-,60,...,37,19,-,1,26,1,-,-,1176,456
6,2019,중랑구,57,"8,365","2,774","2,759",471,354,-,74,...,-,-,-,-,-,212,64,-,449,"1,156"
7,2019,성북구,78,"8,449","2,722","1,282","1,014","1,656",66,65,...,4,-,-,-,9,5,97,-,853,547
8,2019,강북구,31,"7,789","3,510",934,324,497,284,-,...,5,-,-,140,-,-,"1,007",-,575,410
9,2019,도봉구,63,"9,572","4,914",323,779,"2,095",6,61,...,15,-,-,-,-,214,15,-,47,"1,070"
10,2019,노원구,50,"14,489","6,505","3,336","1,165","1,612",-,285,...,-,-,-,26,58,150,32,1,142,"1,135"
11,2019,은평구,35,"9,880","4,324","1,653",680,"1,748",-,16,...,-,9,-,-,-,3,-,-,443,582
12,2019,서대문구,39,"8,627","3,474","1,890",721,732,-,25,...,10,5,4,-,-,70,-,-,493,"1,120"
13,2019,마포구,92,"14,538","3,353","3,581","3,056","1,096",-,474,...,-,-,-,-,64,-,124,93,1280,348
14,2019,양천구,69,"13,501","5,622","3,992","1,065",956,-,74,...,-,4,-,-,-,197,-,-,784,595
15,2019,강서구,55,"13,719","3,977",706,"2,231","2,508",-,"1,651",...,-,110,-,-,-,59,282,-,1426,568
16,2019,구로구,81,"11,548","3,594","1,527","1,884","2,157",13,3,...,-,17,-,-,-,-,30,26,1082,"1,210"
17,2019,금천구,30,"6,603","3,545","1,024",407,"1,123",-,35,...,-,7,-,-,-,-,5,-,184,69
18,2019,영등포구,114,"18,220","5,879","3,439","3,419","2,952",147,51,...,12,174,-,-,-,-,40,19,1281,651
19,2019,동작구,29,"7,083","2,178",829,"1,421","1,127",-,116,...,-,-,-,-,-,206,7,-,397,794
20,2019,관악구,32,"10,154","2,280","2,188",185,"2,416",-,95,...,-,-,-,-,-,"1,120",59,-,249,"1,194"
21,2019,서초구,56,"16,548","3,800","5,036","3,409",254,-,"1,159",...,-,721,-,-,-,91,-,-,446,"1,143"
22,2019,강남구,60,"23,349","7,210","7,559","2,991","2,455",-,864,...,65,-,-,-,-,-,-,-,768,913
23,2019,송파구,99,"22,858","11,894","4,180","2,400",992,-,14,...,722,329,-,-,-,-,215,-,1651,450
24,2019,강동구,66,"17,152","5,474","4,284","2,417","2,309",-,-,...,-,-,-,-,-,-,-,-,642,"1,969"

In [6]:
sample10000_means = []
sample10000 = tree['이팝나무'].sample(10000,random_state=123, replace=True)  ## 10000개 데이터 중복추출
sample10000_means.append(sample10000.mean())
sample10000_means

[687.5389]

In [7]:
pop_means =[] 
pop_means= np.array(pop_means)
pop_means = tree.이팝나무.mean()
pop_means  ## 모집단 평균 = 688.64 , 샘플링 평균 = 622.73 으로 같지않음

688.64

In [8]:
from scipy import stats
sample10000_ttest = stats.ttest_1samp(sample10000, pop_means)
pv1 = sample10000_ttest.pvalue
pv1    ## p-value = 0.79로 0.05보다 크므로 귀무가설을 채택

0.7910849648113394

# 2. Two-Sample T-test
두 샘플의 평균값을 비교하는 검정 방법입니다. 

$H_0$ : $\mu_1 = \mu_2$

$H_a$ : $\mu_1 ≠ \mu_2$

- 단측 검정(One-tailed Test)을 사용하여 평균 `느티나무` 수와 평균 `왕벚나무` 수를 비교하는 가설검정을 시행하세요. 
  - `서울시`, `공원녹지사업소`, `시설관리공단` 데이터는 제외합니다. 
  - scipy 라이브러리의 `.ttest_ind()`를 사용합니다.

    https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html
  - '평균 느티나무 수가 왕벚나무 수보다 통계적으로 유의미하게 크다'는 가설검정 결과의 pvalue 값을 `pv2`에 저장하세요. 
  - '평균 왕벚나무 수가 느티나무 수보다 통계적으로 유의미하게 크다'는 가설검정 결과의 pvalue 값을 `pv3`에 저장하세요. 
  - 평균 `느티나무` 수와 평균 `왕벚나무` 수를 비교하는 가설검정 결과를 `ans`에 저장하세요. 이때 `ans`는 다음 세 가지 중 하나입니다. 
    - 느티나무 (평균 느티나무 수가 왕벚나무 수보다 통계적으로 유의하게 큰 경우)
    - 왕벚나무 (평균 왕벚나무 수가 느티나무 수보다 통계적으로 유의하게 큰 경우)
    - 같다. (통계적으로 유의미한 차이가 없다.)

In [11]:
# 1번은 모집단데이터라고 가정, 2번은 샘플데이터로 가정 (디코에 이게 샘플데이터라는 지혜님 설명을 나중에 2번풀때 읽음)
tree['느티나무'] = tree['느티나무'].str.replace(',','').astype(int)
tree['왕벚나무'] = tree['왕벚나무'].str.replace(',','').astype(int)

AttributeError: ignored

In [26]:
pop2 = tree.느티나무
pop2 = np.array(pop2)
pop3 = tree.왕벚나무
pop3 = np.array(pop3)
print(pop2.var())
print(pop3.var())
print('pop2평균 = ',pop2.mean())
print('pop3평균 = ', pop3.mean())

1031923.9456
665717.84
pop2평균 =  1415.12
pop3평균 =  1292.0

In [28]:
pv2 = stats.ttest_ind(pop2, pop3, alternative='greater',equal_var = False).pvalue
pv3 = stats.ttest_ind(pop3, pop2, alternative='greater',equal_var = False).pvalue
print('pv2 = ',pv2)
print('pv3 = ',pv3)   #pv2 = 0.32  pv3 = 0.68

if pv2 < 0.05 :   ## 귀무가설: 느티나무가 왕벚나무보다 작거나같다 인데  p값이 0.05 이하면 귀무가설 기각후 대립가설채택 = 느티나무가 왕벚나무보다 크다
  ans = '느티나무'
elif pv3 < 0.05 :  ## 귀무가설 : 왕벚나무가 느티나무보다 작거나같다   p값이 0.05 이하면 귀무가설 기각후 대립가설채택 = 왕벚나무가 느티나무보다 크다
  ans = '왕벚나무'
else :            ## 둘다 p가 0.05 이상이면 '느티나무가 왕벚나무보다 작거나같다 and 왕벚나무가 느티나무보다 작거나같다' = 같다 
  ans = '같다'
print(ans)

pv2 =  0.322803351843706
pv3 =  0.677196648156294
같다

# 🔥 도전과제

**다음은 대표적인 4가지 sampling 방식을 설명한 것입니다.**

- Simple Random Sampling
  
    : 모집단에서 무작위로 추출하는 방식입니다.

    <img src = 'https://i.imgur.com/VveWJJf.png' width=150>
- Systematic Sampling

    : 모집단에서 규칙을 가지고 추출하는 방식입니다. ex) 1, 6, 11, 16, ... 번째의 데이터 선택 

    <img src = 'https://i.imgur.com/u5otXyy.png' width=150> 
- Stratified Random Sampling

    : 모집단을 여러 그룹으로 나누고, 각 그룹에서 무작위로 추출하는 방식입니다. ex) 여론 조사에서 나이대별로 무작위 추출 

    <img src = 'https://i.imgur.com/3KPzuDx.png' width=150>
- Cluster Sampling

    : 모집단을 여러 그룹으로 나누고, 특정 그룹을 무작위로 선택하는 방식입니다. 

    <img src = 'https://i.imgur.com/m9eJ3nN.png' width=150>

## Sampling

- 위의 4가지 sampling 방식을 구현해 봅니다.

  - 모집단은 1부터 100까지 담은 numpy array이며, Sampling 하는 데이터 수는 20개입니다.

  - Stratified Random Sampling을 위한 그룹을 나누는 기준은 1-10, 11-20, ... 과 같은 방식입니다.

  - Cluster Sampling에서 그룹을 나누는 기준은 5로 나눴을 때의 나머지 값입니다. (0,1,2,3,4)

In [10]:
# 이 곳에 답안을 작성하시기 바랍니다.